#!/usr/bin/env python3
"""Regenerate progress/tracker.md from plan/roadmap/phase-*.md.

Preserves existing Status / Conf / Last touched / score values for IDs that still exist,
so it is safe to re-run after editing the roadmap. Usage: python3 tools/gen_tracker.py
"""
import glob, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACKER = os.path.join(ROOT, "progress", "tracker.md")
CONCEPT_TYPES = ("L", "DD", "C", "LAB", "WE", "AR")


def short(txt):
    b = re.search(r"(★\s*)?\*\*(.+?)\*\*", txt)
    if b and txt.index("**") < 25:
        star = "★" in (b.group(1) or "") or txt.lstrip("0123456789. ").startswith("★")
        return star, b.group(2).rstrip(":")
    t = re.sub(r"[`*]", "", txt)
    star = t.startswith("★")
    return star, re.split(r" · |: |; ", t.lstrip("★ "))[0]


def key_of(name):
    n = re.sub(r",? v\d.*|\s*\(.*|^Design exercise: ", "", name).strip()
    n = n[:1].upper() + n[1:]
    return n, re.sub(r"[^a-z0-9]", "", re.sub(r"#\d+|★", "", n.lower()))


# keep previously recorded progress
old = {}
if os.path.exists(TRACKER):
    for line in open(TRACKER):
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if len(c) == 6 and re.match(r"^\d+\.\d+\.\d+$", c[0]):
            old[c[0]] = c[3:6]
        elif len(c) == 6 and c[0] and not c[0].startswith("-") and c[0] != "Design":
            old["D:" + key_of(c[0])[1]] = (c[2], c[4], c[5])
        elif len(c) == 4 and c[0].startswith("Gate "):
            old[c[0]] = c[1:4]

rows, designs = [], {}
for f in sorted(glob.glob(os.path.join(ROOT, "plan", "roadmap", "phase-*.md"))):
    ph = int(re.search(r"phase-(\d+)", f).group(1))
    rows.append(("H", open(f).readline().strip("# \n")))
    for line in open(f):
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if not re.match(r"^\d+\.\d+\.\d+$", c[0]):
            continue
        sid, typ, txt = (c[0], "COLD", c[1]) if len(c) == 2 else (c[0], c[1], c[2])
        star, name = short(txt)
        if typ == "COLD" and ph in (9, 10):
            if re.match(r"^R\b", name):
                continue
            n, k = key_of(name)
            designs.setdefault(k, {"name": n, "learn": [], "cold": []})["cold"].append(sid)
        elif typ == "F" and ph <= 8:
            n, k = key_of(name)
            designs.setdefault(k, {"name": n, "learn": [], "cold": []})["learn"].append(sid)
        elif typ in CONCEPT_TYPES:
            rows.append((sid, typ, name, star))

out = ["# Curriculum Tracker", "",
       "Generated by `tools/gen_tracker.py` from `plan/roadmap/` (re-run after roadmap edits; progress is preserved).",
       "One row per concept / worked-example / architecture-review session. Status: ⬜ not started ·",
       "🟨 in progress · ✅ mastered (explain + apply + defend + retain). Conf 1–5. ★ = added beyond the README."]
for r in rows:
    if r[0] == "H":
        out += ["", f"## {r[1]}", "", "| ID | Type | Topic | Status | Conf | Last touched |", "|---|---|---|---|---|---|"]
    else:
        st, cf, lt = old.get(r[0], ("⬜", "", ""))
        out.append(f"| {r[0]} | {r[1]} | {'★ ' if r[3] else ''}{r[2]} | {st} | {cf} | {lt} |")
clean, i = [], 0
while i < len(out):
    if out[i].startswith("## ") and (i + 4 >= len(out) or not re.match(r"\| \d", out[i + 4])):
        i += 4
        continue
    clean.append(out[i]); i += 1
out = clean + ["", "## Designs", "",
               "Learning pass(es) inside the phase → timed cold pass in Phase 9 (staff: Phase 10). Best score /120.", "",
               "| Design | Learning pass | Learn score | Cold pass | Cold score | Attempts |", "|---|---|---|---|---|---|"]
for k, d in designs.items():
    ls, cs, at = old.get("D:" + k, ("", "", ""))
    out.append(f"| {d['name']} | {', '.join(d['learn']) or '—'} | {ls} | {', '.join(d['cold']) or '—'} | {cs} | {at} |")
out += ["", "## Baseline & final", "", "| Session | Date | Score |", "|---|---|---|",
        "| 0.0.2 Baseline (URL Shortener, cold) | | |", "| 11.3.1 Baseline redo | | |",
        "", "## Gates", "", "| Gate | Status | Attempts | Passed on |", "|---|---|---|---|"]
for g in range(12):
    st, at, po = old.get(f"Gate {g}", ("⬜", "", ""))
    out.append(f"| Gate {g} | {st} | {at} | {po} |")
open(TRACKER, "w").write("\n".join(out) + "\n")
n = sum(1 for r in rows if r[0] != "H")
print(f"{n} concept/WE/AR rows, {len(designs)} designs -> {TRACKER}")
